###############################################################################
# Sciquill configuration 
# sqdir - points to your sciquill repository
# sqtype - sciquill media type: 'manuscript', 'cv', or 'grant'
# then, include sciquill.make for default recipes and variables

sqdir = ${SQDIR}
sqtype = grant_simple
include $(sqdir)/sciquill.make
